# Generated by Django 6.0.2 on 2026-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_influencerprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='accept_custom_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='accept_dm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='authenticator_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='auto_withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instant_payouts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='login_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_announcements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_booking_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_browser_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_inapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_new_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_payment_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='notif_weekly_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='show_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='show_earnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='show_rate_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='sms_auth',
            field=models.BooleanField(default=True),
        ),
    ]
