# Generated by Django 6.0.2 on 2026-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_influencerprofile_accept_custom_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_brand_package',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_instagram_post',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_instagram_story',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_twitter_thread',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_youtube_dedicated',
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_youtube_integration',
            field=models.IntegerField(default=8000),
        ),
    ]
